# This shell is for running apps generated by the BA basic compiler in the RISC-V OS emulator rvos.
# This abstraction of _start and riscv_print_text allows the same apps to run on
# physical hardware: the Kendryte K210 Sipeed Maixduino Board. That environment invokes bamain, not main.

.text
.align 3
.globl _start
.type _start, @function
_start:
        .cfi_startproc
        jal     main

        li      a0, 0  # exit code
        li      a7, 1  # exit
        ecall
        .cfi_endproc

.globl riscv_print_text
.type riscv_print_text, @function
riscv_print_text:
        .cfi_startproc
        addi    sp, sp, -32
        sd      ra, 16(sp)

        li      a7, 2  # print asciiz string in a0
        ecall

        ld      ra, 16(sp)
        addi    sp, sp, 32
        jr      ra
        .cfi_endproc

